[build]
  command = "make build"
  functions = "functions"
  publish = "site"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/toddbirchard/netlify-metadata-scraper"